apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintestq-app
  namespace: grchronis-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fintestq-app
  template:
    metadata:
      labels:
        app: fintestq-app
    spec:
      containers:
        - name: fintestq-app
          image: 1171821/fintestq-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MP_MESSAGING_OUTGOING_STOCK_TRADE_DATA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: MP_MESSAGING_OUTGOING_STOCK_FINANCIAL_DATA_BOOTSTRAP_SERVERS
              value: kafka:9092
#          readinessProbe:
#            httpGet:
#              path: /q/health/ready
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 5
#          livenessProbe:
#            httpGet:
#              path: /q/health/live
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fintestq-app
  namespace: grchronis-dev
spec:
  selector:
    app: fintestq-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fintestq-app
  namespace: grchronis-dev
spec:
  to:
    kind: Service
    name: fintestq-app
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
